pluginClass=com.morpheusdata.system.example.SystemExamplePlugin
pluginVersion=1.0.0
code=morpheus-system-example
name=Arcus System Example Plugin
description=Example plugin demonstrating System Provider, Configuration Workflow, Wizards, Forms, and Custom Input Types
author=Morpheus Data
logo=assets/morpheus.svg
logoDark=assets/morpheus.svg
color=#30B3E6
labels=System Provider, Configuration Workflow, Wizards
sourceRepo=https://github.com/gomorpheus/morpheus-plugin-core
minApplianceVersion=7.0.0
